services:
  socialbackend:
    container_name: socialnetworkBE
    build: ./
    restart: always
    ports:
      - 5035:5035
    networks:
      - frazileserver
    depends_on:
      - fzsocialDB

  fzsocialDB:
    container_name: fzsocialnetworkDB
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fzsocial
      MONGO_INITDB_ROOT_PASSWORD: "Y7!qP3mZ9PvL2Xr5#Tn8Kc4WfH1sD6B0u"
      MONGO_INITDB_DATABASE: fzsocialnetworkDB
    volumes:
      - fzsocialdatabase:/data/db
    ports:
      - 5034:27017
    networks:
      - frazileserver

volumes:
  fzsocialdatabase:

networks:
  frazileserver:
    external: true
