services:
  fzsocialbackend:
    container_name: fzsocialnetworkBE
    build: ./
    restart: always
    ports:
      - 5035:5035
    networks:
      - frazileserver
    depends_on:
      - fzsocialDB

fzsocialDB:
  container_name: fzsocialnetworkDB
  image: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: fzsocial
    MONGO_INITDB_ROOT_PASSWORD: "Xtua6G#hYI@k39NFMVWcqwy5d8Px*P"
    MONGO_INITDB_DATABASE: fzsocialnetworkDB
  volumes:
    - fzsocialDB:/data/db
  ports:
    - 5036:27017
  networks:
    - frazileserver

volumes:
  fzsocialDB:

networks:
  frazileserver:
    external: true
